spring:
  application:
    name: aston-service
  profiles:
    active: default
  config:
    import: "optional:configserver:http://config-server:8881"

eureka:
  client:
    serviceUrl:
      defaultZone: "http://eureka-server:8761/eureka/"
